version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jenkins-ci.plugins:jackson2-api
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: io.jenkins.blueocean:blueocean
    versions:
    - 1.24.4
    - 1.24.5
  - dependency-name: org.jenkins-ci.plugins:plugin
    versions:
    - "4.15"
    - "4.16"
    - "4.17"
  - dependency-name: io.jenkins.plugins:warnings-ng
    versions:
    - 8.10.0
    - 8.10.1
    - 8.7.0
    - 8.8.0
    - 8.9.0
    - 8.9.1
    - 8.9.2
  - dependency-name: org.jenkins-ci.plugins:matrix-auth
    versions:
    - 2.6.5
  - dependency-name: org.jenkins-ci.plugins:role-strategy
    versions:
    - "3.1"
  - dependency-name: org.jenkins-ci.plugins:sidebar-link
    versions:
    - 1.11.0
